#!zsh
# This script is used to install dotfile into devcontainer

# install zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# install zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# install starship
# save install script to /tmp
curl -fsSL https://starship.rs/install.sh -o /tmp/install.sh
sh /tmp/install.sh --yes > /dev/null

DIR=$(SELF=$(dirname "$0") && bash -c "cd \"$SELF\" && pwd")


# Soft link .dotfile
link_home_file() {
  # if $1 is already a symlink, then overwrite it.
  if [ -L ~/$2 ]; then
    rm ~/$2
    ln -s $DIR/$1 ~/$2
    echo "Overwrite $2"
    return
  fi
  
  # if $1 is a file, then backup it and link it.
  if [ -f ~/$2 ]; then
    mv ~/$2 ~/$2.bak
  else
    echo "No $2 found. Linked it."
  fi
  ln -s $DIR/$1 ~/$2
}


# Install tmux, git, bat
if [ -x "$(command -v apt_get)" ]; then
  echo 'Install with apt_get.'
  apt_get update
  apt_get install -y tmux git bat
fi

if [ -x "$(command -v yum)" ]; then
  echo 'Install with yum.'
  # tmux with newest version must be installed with this repo
  yum install -y http://galaxy4.net/repo/galaxy4-release-7-current.noarch.rpm
  yum install -y tmux git

  # Install bat
  wget -c http://repo.openfusion.net/centos7-x86_64/bat-0.7.0-1.of.el7.x86_64.rpm --no-check-certificate
  yum install -y bat-0.7.0-1.of.el7.x86_64.rpm
  rm bat-0.7.0-1.of.el7.x86_64.rpm
fi

# Link all files
link_home_file config/.zshrc .zshrc
link_home_file config/.bash_aliases .bash_aliases
link_home_file config/.bashrc .bashrc
link_home_file config/.gitconfig .gitconfig
link_home_file config/.tmux.conf .tmux.conf
# if .config does not exist, create it
if [ ! -d ~/.config ]; then
  mkdir ~/.config
fi
link_home_file config/starship.toml .config/starship.toml

# source .bashrc or .zshrc
exec zsh