# Allowing use mouse in tmux
# macOS only, find from https://unix.stackexchange.com/questions/318281/how-to-copy-and-paste-with-a-mouse-with-tmux
set -g mouse on
# the config of tmux-better-mouse-mode. this make scrolling more smooth
set -g @scroll-speed-num-lines-per-scroll 2
# set the default shell to zsh
set -g default-command /bin/zsh

# Set status bar style
set -g window-status-separator " "
set -g status-style fg=green,bg=grey8
set -g window-status-current-format "#[bold,fg=black,bg=green] #I:#W#F "
set -g window-status-format "#[fg=green,bg=gray15] #I:#W#F "

# Easy reload tmux config with r key
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
# This line fail on CentOS server so I comment it out
# run '~/.tmux/plugins/tpm/tpm > /dev/null 2>&1'